CREATE DATABASE spareshop;
USE spareshop;

CREATE TABLE buyer (
	id INT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL,
    address VARCHAR(100) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE shop (
	id INT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL,
    address VARCHAR(100) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE buyer
MODIFY username VARCHAR(100) NOT NULL UNIQUE,
MODIFY email VARCHAR(100) NOT NULL UNIQUE,
MODIFY password VARCHAR(100) NOT NULL,
MODIFY address VARCHAR(100) NOT NULL;

ALTER TABLE shop
MODIFY username VARCHAR(100) NOT NULL UNIQUE,
MODIFY email VARCHAR(100) NOT NULL UNIQUE,
MODIFY password VARCHAR(100) NOT NULL,
MODIFY address VARCHAR(100) NOT NULL;


