"""try migration 2

Revision ID: a4e6b75cff2e
Revises: 38f5c04993f4
Create Date: 2024-03-19 15:55:54.331069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4e6b75cff2e'
down_revision = '38f5c04993f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('address', ['address'], unique=True)

    # ### end Alembic commands ###
